name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack-server:7.0.6-RC9
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Build the project
        uses: gradle/gradle-build-action@v1
        with:
          arguments: build -Predis.uri=redis://redis
